# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160627_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('fileway', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
